apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048
  labels:
    app: "2048"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 2048
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
        - name: 2048
          image: alexwhen/docker-2048
          ports:
            - containerPort: 80