kind: Service
metadata:
  name: game-2048-service
  labels:
    app: "game-2048"
spec:
  type: LoadBalancer
  selector:
    app: "game-2048"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80